Update manage

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -2,8 +2,7 @@
 export MSYS_NO_PATHCONV=1
 export DOCKERHOST=${APPLICATION_URL-$(docker run --rm --net=host codenvy/che-ip)}
 
-# disable exit on non zero
-set +e
+set -e
 
 S2I_EXE=s2i
 if [ -z $(type -P "$S2I_EXE") ]; then
@@ -168,7 +167,8 @@ build-api() {
   BASE_IMAGE="registry.access.redhat.com/dotnet/dotnet-21-rhel7:latest"
   BASE_IMAGE_NAME="dotnet-21-rhel7:latest"
   
-  docker pull $BASE_IMAGE
+  # do not fail if we can't pull the image.
+  docker pull $BASE_IMAGE || true
   docker tag $BASE_IMAGE $BASE_IMAGE_NAME
   echo -e "\nBuilding API image from ${BASE_IMAGE_NAME}..."
   
